addi $t0, $zero, 3
addi $t1, $zero, 3
addi $t1, $zero, 2
beq $t0, $t1, finish
addi $t2, $zero, 6
finish: sw $t2, 2($zero)
addi $zero, $zero, 0
addi $zero, $zero, 0
addi $zero, $zero, 0
addi $zero, $zero, 0
